//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.01 at 02:37:37 PM IST 
//


package com.vikas.test.weather.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for forecast complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="forecast">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time" type="{}time" maxOccurs="50" minOccurs="0"/>
 *         &lt;element name="symbol" type="{}symbol" minOccurs="0"/>
 *         &lt;element name="precipitation" type="{}precipitation" minOccurs="0"/>
 *         &lt;element name="windDirection" type="{}windDirection" minOccurs="0"/>
 *         &lt;element name="windSpeed" type="{}windSpeed" minOccurs="0"/>
 *         &lt;element name="temperature" type="{}temperature" minOccurs="0"/>
 *         &lt;element name="feels_like" type="{}feels_like" minOccurs="0"/>
 *         &lt;element name="pressure" type="{}pressure" minOccurs="0"/>
 *         &lt;element name="humidity" type="{}humidity" minOccurs="0"/>
 *         &lt;element name="clouds" type="{}clouds" minOccurs="0"/>
 *         &lt;element name="visibility" type="{}visibility" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "forecast", propOrder = {
    "time",
    "symbol",
    "precipitation",
    "windDirection",
    "windSpeed",
    "temperature",
    "feelsLike",
    "pressure",
    "humidity",
    "clouds",
    "visibility"
})
public class Forecast {

    protected List<Time> time;
    protected Symbol symbol;
    protected Precipitation precipitation;
    protected WindDirection windDirection;
    protected WindSpeed windSpeed;
    protected Temperature temperature;
    @XmlElement(name = "feels_like")
    protected FeelsLike feelsLike;
    protected Pressure pressure;
    protected Humidity humidity;
    protected Clouds clouds;
    protected Visibility visibility;

    /**
     * Gets the value of the time property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the time property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Time }
     * 
     * 
     */
    public List<Time> getTime() {
        if (time == null) {
            time = new ArrayList<Time>();
        }
        return this.time;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link Symbol }
     *     
     */
    public Symbol getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link Symbol }
     *     
     */
    public void setSymbol(Symbol value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the precipitation property.
     * 
     * @return
     *     possible object is
     *     {@link Precipitation }
     *     
     */
    public Precipitation getPrecipitation() {
        return precipitation;
    }

    /**
     * Sets the value of the precipitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Precipitation }
     *     
     */
    public void setPrecipitation(Precipitation value) {
        this.precipitation = value;
    }

    /**
     * Gets the value of the windDirection property.
     * 
     * @return
     *     possible object is
     *     {@link WindDirection }
     *     
     */
    public WindDirection getWindDirection() {
        return windDirection;
    }

    /**
     * Sets the value of the windDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindDirection }
     *     
     */
    public void setWindDirection(WindDirection value) {
        this.windDirection = value;
    }

    /**
     * Gets the value of the windSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link WindSpeed }
     *     
     */
    public WindSpeed getWindSpeed() {
        return windSpeed;
    }

    /**
     * Sets the value of the windSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindSpeed }
     *     
     */
    public void setWindSpeed(WindSpeed value) {
        this.windSpeed = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link Temperature }
     *     
     */
    public Temperature getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Temperature }
     *     
     */
    public void setTemperature(Temperature value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the feelsLike property.
     * 
     * @return
     *     possible object is
     *     {@link FeelsLike }
     *     
     */
    public FeelsLike getFeelsLike() {
        return feelsLike;
    }

    /**
     * Sets the value of the feelsLike property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeelsLike }
     *     
     */
    public void setFeelsLike(FeelsLike value) {
        this.feelsLike = value;
    }

    /**
     * Gets the value of the pressure property.
     * 
     * @return
     *     possible object is
     *     {@link Pressure }
     *     
     */
    public Pressure getPressure() {
        return pressure;
    }

    /**
     * Sets the value of the pressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pressure }
     *     
     */
    public void setPressure(Pressure value) {
        this.pressure = value;
    }

    /**
     * Gets the value of the humidity property.
     * 
     * @return
     *     possible object is
     *     {@link Humidity }
     *     
     */
    public Humidity getHumidity() {
        return humidity;
    }

    /**
     * Sets the value of the humidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Humidity }
     *     
     */
    public void setHumidity(Humidity value) {
        this.humidity = value;
    }

    /**
     * Gets the value of the clouds property.
     * 
     * @return
     *     possible object is
     *     {@link Clouds }
     *     
     */
    public Clouds getClouds() {
        return clouds;
    }

    /**
     * Sets the value of the clouds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clouds }
     *     
     */
    public void setClouds(Clouds value) {
        this.clouds = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    public Visibility getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

}
