//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.01 at 02:37:37 PM IST 
//


package com.vikas.test.weather.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vikas.test.weather.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vikas.test.weather.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Weatherdata }
     * 
     */
    public Weatherdata createWeatherdata() {
        return new Weatherdata();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Sun }
     * 
     */
    public Sun createSun() {
        return new Sun();
    }

    /**
     * Create an instance of {@link Forecast }
     * 
     */
    public Forecast createForecast() {
        return new Forecast();
    }

    /**
     * Create an instance of {@link Symbol }
     * 
     */
    public Symbol createSymbol() {
        return new Symbol();
    }

    /**
     * Create an instance of {@link Visibility }
     * 
     */
    public Visibility createVisibility() {
        return new Visibility();
    }

    /**
     * Create an instance of {@link Pressure }
     * 
     */
    public Pressure createPressure() {
        return new Pressure();
    }

    /**
     * Create an instance of {@link Clouds }
     * 
     */
    public Clouds createClouds() {
        return new Clouds();
    }

    /**
     * Create an instance of {@link FeelsLike }
     * 
     */
    public FeelsLike createFeelsLike() {
        return new FeelsLike();
    }

    /**
     * Create an instance of {@link Precipitation }
     * 
     */
    public Precipitation createPrecipitation() {
        return new Precipitation();
    }

    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link Humidity }
     * 
     */
    public Humidity createHumidity() {
        return new Humidity();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link WindDirection }
     * 
     */
    public WindDirection createWindDirection() {
        return new WindDirection();
    }

    /**
     * Create an instance of {@link WindSpeed }
     * 
     */
    public WindSpeed createWindSpeed() {
        return new WindSpeed();
    }

}
